# Project: Seri 1 Tamrin 6
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Seri\ 1\ Tamrin\ 6.o"
LINKOBJ  = "Seri 1 Tamrin 6.o"
LIBS     = -L"F:/Software/Dev-Cpp/MinGW64/lib" -L"F:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Software/Dev-Cpp/MinGW64/include" -I"F:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Software/Dev-Cpp/MinGW64/include" -I"F:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Seri 1 Tamrin 6.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Seri\ 1\ Tamrin\ 6.o": Seri\ 1\ Tamrin\ 6.c
	$(CC) -c "Seri 1 Tamrin 6.c" -o "Seri 1 Tamrin 6.o" $(CFLAGS)
